{{- if (include "kotatsu.createStorageSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kotatsu.storageSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kotatsu.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.storage.secretKeys.accessKey }}: {{ .Values.storage.accessKey | b64enc | quote }}
  {{ .Values.storage.secretKeys.secretKey }}: {{ .Values.storage.secretKey | b64enc | quote }}
{{- end }}
